### ISSUE TITLE
Does this work with non-avr atmel microcontrollers?

### ISSUE THREAD

**Issue by aj22r** [xoriath/vscode-atmel-debug#1]
I'd like to use visual studio code to debug Atmel SAM microcontrollers and I'm wondering if it is possible to do with this.

**Comment by xoriath** [comment]
Maybe... Feel free to try...

**Comment by aj22r** [comment]
Well I can't get this to work at all because when i open the vsix file it says that the file is not a valid VSIX package.

**Comment by aj22r** [comment]
Okay so I'm getting 'Incorrect type. Expected "any"' in launch.json on "connectionProperties" and "interfaceProperties". I'm using the default launch.json

**Comment by aj22r** [comment]
Fixed. I used cortex-debug instead.
